#logging:
#  config: classpath:logback.xml

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO
    org.springframework: INFO
    com.pongift.common.mapper: TRACE
    com.pongift.naver: DEBUG

server:
  port: 8380
  servlet:
    context-path: /
    session:
      cookie:
        name: JSESSIONID
  error:
    whitelabel:
      enabled: false

spring:
  thymeleaf:
    cache: false
  devtools:
    livereload:
      enabled: true
  resources:
    static-locations: classpath:/static/
  freemarker:
    template-loader-path: classpath:/static/html
    suffix: .html
    charset: utf-8
    cache: true
    enabled: true
    content-type: text/html
    check-template-location: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:localhost;DB_CLOSE_ON_EXIT=FALSE
    username: admin
    password:
    hikari:
      driver-class-name: org.h2.Driver
      connectionInitSql: SELECT 1 FROM DUAL
      connection-timeout: 30000
      idle-timeout: 600000
      connection-test-query: SELECT 1 FROM DUAL
      auto-commit: false
      register-mbeans: true
      leak-detection-threshold: 2000
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  output:
    ansi:
      enabled:always
  servlet:
      multipart:
        enabled: true
        max-file-size: 10240MB
        max-request-size: 10240MB

# ===============================
# Naver API (SandBox)
# ===============================

#naver:
#  api:
#    requestId: pongift
#    sellerId: ncp_1njhs3_02
#    version: 4.1
#    license: 0100010000714ec3c698110a0f4165bf28a5626d83327d49327b2124dab9c1190b1f65c0f3
#    key: AQABAAD9zJEf+D3umyddqxAhejnD0WJu28+4jU0x52TUoAUsjg==
#    url: https://sandbox.api.naver.com

naver:
  api:
    requestId: platfos0914
    sellerId: ncp_1nzozo_01
    version: 4.1
    license: 0100010000655b99bb89d63e142bac6ad52cdd2042b27d161a11c824c4772955124fb3700d
    key: AQABAAAv6uybmSobV6CVJa1yyXBEClc9lhMkSyiiIIzJfUJq0g==
    url: http://ec.api.naver.com
#  commerce:
#    clientId: 4YZjflsMFVXVkpSKjFGlfN
#    clientSecret: $2a$04$q8Cz0tPqkXVyQJBqfJEqPe
#    host: https://sandbox-api.commerce.naver.com/partner
  commerce:
    clientId: 1vXvGVwo90Hrs8fdbcMutS
    clientSecret: $2a$04$07wPuyUMMTSoFlPcKIgQze
    host: https://api.commerce.naver.com/partner
platfos:
  api:
    url: http://tb.pongift.com:914